### ISSUE TITLE
Elaborate README.md

### ISSUE THREAD

**Issue by RosaWagner** [NaN-xyz/Rubik-Filtered#3]
Should contain at least: 

- Description of the family and process
- Images
- Link to Glyphs Filters

**Comment by davelab6** [comment]
@NaN-xyz would you be able to take this in?

**Comment by NaN-xyz** [comment]
I can do this.

**Comment by NaN-xyz** [comment]
FYI I've almost re-generated all the fonts with all the final meta data and metrics. I just need to run through and do a bit of bug-hunting and re-re-generating. Re.
